# -*- coding: utf-8 -*-
"""Evidencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1quHLF_OvZ7YJSkDarIBclYY_jYW72nb4

##Actividad Integradora Modulo 6

Camila Murillo - A00828860

18 de junio 2023
"""

#pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
#import plotly as px
#import plotly.figure_factory as ff
#from bokeh.plotting import figure
import matplotlib.pyplot as plt

st.title('Police Incident Reports from 2018 to 2020 in San Francisco')

image = "sf.jpg"
st.image(image)

df = pd.read_csv("Policia.csv")
#st.dataframe(df)
st.markdown('The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution.')

mapa = pd.DataFrame()
mapa['Date'] = df['Incident Date']
mapa['Day'] = df['Incident Day of Week']
mapa['Year'] = df['Incident Year']
mapa['Police District'] = df['Police District']
mapa['Neighborhood'] = df['Analysis Neighborhood']
mapa['Incident Category'] = df['Incident Category']
mapa['Incident Subcategory'] = df['Incident Subcategory']
mapa['Resolution'] = df['Resolution']

#mapa=pd.DataFrame(df['Latitude'], df['Longitude'])
mapa['lat'] = df['Latitude']
mapa['lon'] = df['Longitude']

mapa=mapa.dropna()
#st.map(mapa.astype(int))

subset_data2 = mapa
police_district_input = st.sidebar.multiselect(
'Police District',
mapa.groupby('Police District').count().reset_index()['Police District'].tolist())
if len(police_district_input) > 0:
    subset_data2 = mapa[mapa['Police District'].isin(police_district_input)]

subset_data1 = subset_data2
neighborhood_input = st.sidebar.multiselect(
'Neighborhood',
subset_data2.groupby('Neighborhood').count().reset_index()['Neighborhood'].tolist())
if len(neighborhood_input) > 0:
    subset_data1 = subset_data2[subset_data2['Neighborhood'].isin(neighborhood_input)]

subset_data = subset_data1
incident_input = st.sidebar.multiselect(
'Incident Category',
subset_data1.groupby('Incident Category').count().reset_index()['Incident Category'].tolist())
if len(incident_input) > 0:
    subset_data = subset_data1[subset_data1['Incident Category'].isin(incident_input)]

subset_data3 = mapa
police_district_input = st.sidebar.multiselect(
'Incident Subcategory',
mapa.groupby('Incident Subcategory').count().reset_index()['Incident Subcategory'].tolist())
if len(police_district_input) > 0:
    subset_data3 = mapa[mapa['Incident Subcategory'].isin(police_district_input)]

subset_data

st.markdown('It is important to mention that any police district can answer to any incident, the neighborhood in which it happened is not related to the police district.')
st.markdown('Crime locations in San Francisco')
st.map(subset_data)

st.markdown('Crimes ocurred per day of the week')
st.bar_chart(subset_data['Day'].value_counts())
with st.expander("See explanation"):
    st.write("""The chart above shows the numbers of crimes committed by day in a week""")

st.markdown('Crimes occured per date')
st.line_chart(subset_data['Date'].value_counts())
with st.expander("See explanation"):
    st.write("""The chart above shows the dates of the numbers of crimes committed in the last two years""")

st.markdown('Type of crimes committed')
st.bar_chart(subset_data['Incident Category'].value_counts())
with st.expander("See explanation"):
    st.write("""The chart above shows the different types of crime committed""")

st.markdown('Crimes occured per year')
st.line_chart(subset_data['Year'].value_counts())
with st.expander("See explanation"):
    st.write("""The chart above shows the numbers of crimes committed in the last two years""")

agree = st.button('Click to see Incident Subcategories')
if agree:
  st.markdown('Subtype of crimes committed')
  st.bar_chart(subset_data['Incident Subcategory'].value_counts())

agree1 = st.button('Click to see Analysis Neighborhood')
if agree1:
  st.markdown('Analysis Neighborhood')
  st.bar_chart(subset_data['Neighborhood'].value_counts())

agree2 = st.button('Click to see Police District')
if agree2:
  st.markdown('Analysis by Police District')
  st.bar_chart(subset_data['Police District'].value_counts())

st.markdown('Resolution status')
fig1,ax1 = plt.subplots()
labels = subset_data['Resolution'].unique()
ax1.pie(subset_data['Resolution'].value_counts(),labels=labels, autopct = '%1.1f%%',startangle=20)
st.pyplot(fig1)